# Эффекты размытия и закругления
decoration {
    rounding = 12
    active_opacity = 0.9
    inactive_opacity = 0.8

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }
}

# Внешний вид окон
general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(ee6246ff) rgba(ee9646ff) 45deg
    col.inactive_border = rgba(595959aa)
}

# Автозапуск необходимых компонентов
exec-once = "systemctl --user start caelestia-shell.service"
